
## Path to RNA-seq sample samplesheet
samplesheet: 'samplesheet_replicate.csv'

## Software versions
fastqcVersion: '0.11.9'
trimgaloreVersion: "0.6.7"
salmonVersion: '1.10.0'
multiqcVersion: '1.11'
rVersion: '4.2.2'

## Salmon options
salmon: '/proj/seq/data/salmon_RNAseq_genomes/hg38_cdna/salmon_index/default' # Path to salmon index. 
gcBias: 'TRUE'
seqBias: 'TRUE'
